# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 019b80dce17f297284c706f371659bcebe7aad32d8376d3b112bd5fd2fc7e1f3c98c4c9128b36de2e4e7335de22e90294d91aec4249b6cc8bab5a4bd2ee6adda

test:
  secret_key_base: a1c213ff6f771d46b856bfea0f0bbcd9a7e45f3bf13387e7cd87109c4b710aa89bb4fc5b61a38959d419582d41cdd0869130c1b78409e1fc9aaa1ce2e9d75cac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_key: "117451673535319"
  api_secret: "tZhf7wTr2SQ3Vr7O6VdUmzBs-rg"
